In [ ]:
import torch
torch.__version__

'2.8.0+cu126'

**Tensors**

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# dimensions
scalar.ndim

0

In [ ]:
# to get back scalar number
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

Random Tensors

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3451, 0.3265, 0.4700, 0.4055],
        [0.9073, 0.6994, 0.9341, 0.8915],
        [0.1968, 0.2166, 0.1624, 0.5123]])

In [ ]:
random_tensor = torch.rand(3, 4, 5)
random_tensor

tensor([[[0.0418, 0.4432, 0.5541, 0.3939, 0.7806],
         [0.8506, 0.5211, 0.1242, 0.8485, 0.0017],
         [0.6261, 0.2628, 0.1203, 0.0070, 0.4769],
         [0.9737, 0.2830, 0.8065, 0.2445, 0.3408]],

        [[0.4300, 0.7678, 0.2107, 0.9276, 0.3696],
         [0.9002, 0.8834, 0.5170, 0.0305, 0.1216],
         [0.5473, 0.8841, 0.6545, 0.8779, 0.4452],
         [0.9147, 0.6234, 0.6126, 0.3127, 0.2094]],

        [[0.2167, 0.0685, 0.4025, 0.4792, 0.0019],
         [0.7961, 0.5277, 0.9628, 0.3654, 0.7862],
         [0.1273, 0.9530, 0.5546, 0.8767, 0.1203],
         [0.0925, 0.7114, 0.5147, 0.1198, 0.1016]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# tensor in the common image shape
#  ([height, width, color_channels])

random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

**Zeros** **and** **Ones**

In [ ]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

 **range** **and** **tensors**

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=2)
zero_to_ten

tensor([0, 2, 4, 6, 8])

In [ ]:
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0])

**tensor data type**

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)

float_16_tensor.dtype

torch.float16

**Getting information from tensors**

In [ ]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.0516, 0.9592, 0.7246, 0.7489],
        [0.8385, 0.3313, 0.7892, 0.4944],
        [0.7795, 0.1367, 0.1042, 0.1536]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


**tensor operations**

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [ ]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


*Matrix multiplication*

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)

In [ ]:
# now that right
tensor_T = torch.tensor([[ 7.,  8.,  9.],
                           [10., 11., 12.]], dtype=torch.float32)


In [ ]:
output =torch.matmul(tensor_A, tensor_T)
output

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
tensor_A.shape, tensor_T.shape # inner dimensions must match

(torch.Size([3, 2]), torch.Size([2, 3]))

**transpose**

In [ ]:
tensor_B.T

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [ ]:
tensor_A.shape ,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
#difference
tensor_A.shape ,tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

 **min, max, mean, sum, etc (aggregation)**

In [ ]:
# Creating a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


**Positional min/max**

In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


**Reshaping, stacking, squeezing and unsqueezing**

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
"""Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

So changing the view changes the original tensor too."""

'Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.\n\nSo changing the view changes the original tensor too.'

In [ ]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
### Stack

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [ ]:
# sequeze
# this remove all single dimensions

In [ ]:
print("previous tensor: ",x_reshaped)
p = x_reshaped.shape
print("previous shape: ",p)

# removing extra dimension
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
x_squeezed.shape

previous tensor:  tensor([[5., 2., 3., 4., 5., 6., 7.]])
previous shape:  torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])


torch.Size([7])

In [ ]:
# unsequeze

In [ ]:
print(f"previous tensor: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}\n")

# adding extra dimension
unsqueezed_tensor = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {unsqueezed_tensor}")
print(f"New shape: {unsqueezed_tensor.shape}")

previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
previous shape: torch.Size([7])


New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [ ]:
# permute
# rearrange the order of axes values

In [ ]:



# Creating tensor with specific shape
x_original = torch.rand(size=(224, 224, 3)) # (height , width ,color)
# x_original
x_permuted = x_original.permute(2, 0, 1) # (colour , height , width)
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


**indexing**

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0,1]

tensor([4, 5, 6])

In [ ]:
x[0,0,0]

tensor(1)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

**PyTorch tensors & NumPy**

In [ ]:
import torch
import numpy as np

array = np.arange(1.0 , 8.0)
tensor = torch.from_numpy(array)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7) # creating a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducibility (trying to take the random out of random)

In [ ]:
import torch

# Creating two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B?")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.5709, 0.7253, 0.5216, 0.9059],
        [0.4231, 0.9262, 0.0943, 0.7866],
        [0.9825, 0.0695, 0.0034, 0.2827]])

Tensor B:
tensor([[0.9818, 0.1207, 0.1879, 0.5231],
        [0.3264, 0.2374, 0.2741, 0.5698],
        [0.7543, 0.1570, 0.3163, 0.1921]])

Does Tensor A equal Tensor B?


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
random_seed = 42
torch.manual_seed(seed=random_seed)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(seed=random_seed)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


**Getting a GPU**

1 Google Colab
2 Use your own
3 Cloud computing (AWS, GCP, Azure)

In [ ]:
!nvidia-smi

Mon Nov 10 20:23:24 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   62C    P8             13W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
# check for GPU
import torch
torch.cuda.is_available()

True

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

** Putting tensors (and models) on the GPU**

In [ ]:
# Creating tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

**Moving tensors back to the CPU**

In [ ]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
# tensor_on_gpu.numpy()

In [ ]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')